# Generated by Django 5.2.5 on 2025-08-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_espacio_solicitudespacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
    ]
