# Generated by Django 5.2.5 on 2025-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_fecha_publicacion_noticia_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documento_verificacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_verificacion/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('vecino', 'Vecino'), ('directivo', 'Directivo'), ('administrador', 'Administrador')], default='registrado', max_length=20),
        ),
    ]
