# Generated by Django 5.2.5 on 2025-09-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_documento_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cupo_por_vecino',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='actividad',
            name='permite_acompanantes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcionactividad',
            name='cantidad_acompanantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcionactividad',
            name='nombres_acompanantes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='inscripcionactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.actividad'),
        ),
    ]
