# Generated by Django 5.2.5 on 2025-11-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_actividad_cupo_por_vecino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('es_vecino', models.BooleanField(default=True)),
                ('tipo_consulta', models.CharField(blank=True, choices=[('certificado', 'Certificado'), ('espacio', 'Espacio'), ('proyecto', 'Proyecto'), ('no_reconocido', 'No Reconocido')], max_length=20, null=True)),
                ('vecino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensajes_whatsapp',
            },
        ),
        migrations.CreateModel(
            name='ReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes_problemas',
            },
        ),
    ]
