# Generated by Django 5.2.5 on 2025-11-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mensajewhatsapp_reporteproblema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(default='inactivo', max_length=50)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('datos_contexto', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'conversaciones_whatsapp',
            },
        ),
        migrations.RemoveField(
            model_name='reporteproblema',
            name='vecino',
        ),
        migrations.DeleteModel(
            name='MensajeWhatsApp',
        ),
        migrations.DeleteModel(
            name='ReporteProblema',
        ),
    ]
