# Generated by Django 5.2.5 on 2025-11-15 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversacionwhatsapp_remove_reporteproblema_vecino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juntavecinos',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junta_presidente', to=settings.AUTH_USER_MODEL),
        ),
    ]
