from .authentication import *
from .usuarios import *
from .noticias import *
from .certificados import *
from .espacios import *
from .actividades import *
from .proyectos import *
from .dashboard import *
from .perfiles import *